(()=>{'use strict';
const main=document.querySelector('main');if(!main)return;
const store={get(k,f){try{return JSON.parse(localStorage.getItem('engineering:'+k))??f}catch{return f}},set(k,v){try{localStorage.setItem('engineering:'+k,JSON.stringify(v));return true}catch{return false}}};
const key=location.pathname.split('/').pop(),tools=document.createElement('section');tools.className='reader-tools';tools.setAttribute('aria-label','Reading controls');
tools.innerHTML='<label>Palette <select id="palette"><option value="violet">Violet</option><option value="ocean">Ocean</option><option value="night">Night</option></select></label><label>Text size <select id="text-size"><option value="17">Compact</option><option value="19">Comfortable</option><option value="22">Large</option></select></label><button type="button" id="focus-reader" aria-pressed="false">Focus reading</button><span class="progress-label" aria-live="polite"></span>';
main.prepend(tools);const palette=tools.querySelector('#palette'),size=tools.querySelector('#text-size');palette.value=store.get('theme','violet');if(!palette.value)palette.value='violet';size.value=store.get('size','19');if(!size.value)size.value='19';
function appearance(){document.body.dataset.theme=palette.value;document.body.style.fontSize=size.value+'px'}appearance();palette.onchange=()=>{appearance();store.set('theme',palette.value)};size.onchange=()=>{appearance();store.set('size',size.value)};
tools.querySelector('button').onclick=e=>{const active=document.body.classList.toggle('focus-mode');e.currentTarget.setAttribute('aria-pressed',String(active));e.currentTarget.textContent=active?'Show navigation':'Focus reading'};
const headings=[...main.querySelectorAll('h2[id]')];let done=store.get(key+':done',[]);if(!Array.isArray(done))done=[];
function progress(){tools.querySelector('.progress-label').textContent=headings.length?`${headings.filter(h=>done.includes(h.id)).length} / ${headings.length} sections marked read`:'Explore a notebook to begin'}
for(const h of headings){const b=document.createElement('button');b.className='mark-read';b.type='button';const update=()=>{b.textContent=done.includes(h.id)?'Read ✓ — mark unread':'Mark section read';b.setAttribute('aria-pressed',String(done.includes(h.id)))};update();b.onclick=()=>{done=done.includes(h.id)?done.filter(x=>x!==h.id):[...done,h.id];store.set(key+':done',done);update();progress()};h.after(b)}progress();
const nav=document.querySelector('nav');if(nav){const box=document.createElement('div');box.className='chapter-search';box.innerHTML='<label for="chapter-search">Find a lesson</label><input type="search" id="chapter-search" placeholder="Type a topic…">';nav.querySelector('strong').after(box);box.querySelector('input').oninput=e=>{const query=e.target.value.toLowerCase();nav.querySelectorAll(':scope > ul > li').forEach(li=>li.hidden=!li.textContent.toLowerCase().includes(query))}}
const cards=[...main.querySelectorAll('.card')];if(cards.length){const label=document.createElement('label');label.textContent='Find your next notebook';const input=document.createElement('input');input.type='search';input.placeholder='Try Java, RAG, database…';label.append(input);main.querySelector('.cards').before(label);input.oninput=()=>cards.forEach(c=>c.hidden=!c.textContent.toLowerCase().includes(input.value.toLowerCase()))}
for(const pre of main.querySelectorAll('pre')){const button=document.createElement('button');button.className='copy-code';button.textContent='Copy code or output';button.onclick=async()=>{try{await navigator.clipboard.writeText(pre.textContent);button.textContent='Copied'}catch{button.textContent='Select text to copy; clipboard unavailable'}};pre.before(button)}
if(!headings.length||!/^\d\d-/.test(key))return;
const studio=document.createElement('section');studio.className='studio';studio.setAttribute('aria-label','Interactive learning studio');studio.innerHTML='<h2>Learning studio · predict, then explain</h2><p>Keep a prediction in your own words. Reveal the explanation only after you have tried.</p><label for="prediction">My prediction or question</label><textarea id="prediction" placeholder="I think this happens because…"></textarea><p class="saved-note">Notes stay in this browser; they are not uploaded or graded.</p><details><summary>A self-check before moving on</summary><p>Can you name the input, show the intermediate state, explain the result, and describe one failure? If not, return to the worked example. Being able to repeat a definition is different from being able to trace a system.</p></details>';
const h1=main.querySelector('h1');h1.after(studio);const note=studio.querySelector('textarea');note.value=store.get(key+':note','');note.oninput=()=>{const saved=store.set(key+':note',note.value);studio.querySelector('.saved-note').textContent=saved?'Saved in this browser only; not uploaded or graded.':'Storage unavailable. Copy your note before leaving.'};
const lab=document.createElement('div');lab.innerHTML='<h3>Trace a retry, one step at a time</h3><p>Teaching simulation: a payment receiver remembers a stable operation key. A checkpoint and a payment receipt are separate records.</p><label><input id="dedupe" type="checkbox" checked> Receiver deduplicates by operation key</label><p><button id="next-step" type="button">Next event</button> <button id="reset-step" type="button">Reset trace</button></p><output aria-live="polite" id="trace-output"></output><details><summary>Why did the result change?</summary><p>A crash after the payment but before saving workflow progress leaves the worker unsure. Retrying with the same operation key lets an idempotent receiver return the original receipt. A receiver that ignores the key charges again. This assumes the receiver stores the key and payment atomically; merely including a key in a request is not enough.</p></details>';
studio.append(lab);let step=0;const render=()=>{const dedupe=lab.querySelector('#dedupe').checked;const lines=['1. Job created: operation key PAY-17; checkpoint = pending; charges = 0.','2. Receiver commits payment PAY-17; charges = 1. Worker has not saved completion.','3. Worker crashes. Its durable checkpoint still says pending; charges = 1.',dedupe?'4. Retry PAY-17 finds the original receipt; charges = 1.':'4. Retry is treated as a new payment; charges = 2.','5. Worker records completion. Recovery is finished.'];lab.querySelector('output').textContent=lines.slice(0,step+1).join('\n');lab.querySelector('#next-step').disabled=step===4};lab.querySelector('#next-step').onclick=()=>{step=Math.min(4,step+1);render()};lab.querySelector('#reset-step').onclick=()=>{step=0;render()};lab.querySelector('#dedupe').onchange=render;render();
// Use a topic-specific experiment where a compact numerical trace teaches more.
if (/^(02|09|20)-/.test(key)) {
 lab.innerHTML='<h3>Move one gradient step</h3><p>Training points: (1,2), (2,4). Start w=0, b=0. Mean squared loss = 10; gradients = -10 and -6.</p><label for="rate">Learning rate</label> <input type="range" id="rate" min="0" max="0.6" step="0.01" value="0.1"><output id="gradient-result" aria-live="polite"></output><p>Subtract learning rate × gradient. A large step can overshoot: lower training loss on one step does not establish generalization.</p>';
 const update=()=>{const a=Number(lab.querySelector('input').value),w=10*a,b=6*a,p1=w+b,p2=2*w+b,loss=((p1-2)**2+(p2-4)**2)/2;lab.querySelector('output').textContent=`rate = ${a.toFixed(2)}\nw = ${w.toFixed(2)}, b = ${b.toFixed(2)}\npredictions = ${p1.toFixed(2)}, ${p2.toFixed(2)}\nnew loss = ${loss.toFixed(4)} (${loss<10?'improved':loss>10?'worse':'unchanged'})`};lab.querySelector('input').oninput=update;update();
} else if (/^(06|12|21)-/.test(key)) {
 lab.innerHTML='<h3>Trace lower-bound binary search</h3><label for="target-value">Target (0–15)</label> <input id="target-value" type="range" min="0" max="15" value="4"><output aria-live="polite"></output><p>The interval is [lo, hi). Equality keeps mid as a candidate. Index 5 means no qualifying element.</p>';
 const update=()=>{const a=[2,4,4,9,13],target=Number(lab.querySelector('input').value);let lo=0,hi=a.length,lines=[`array = [${a}], target = ${target}`];while(lo<hi){const mid=lo+Math.floor((hi-lo)/2);lines.push(`lo=${lo}, hi=${hi}, mid=${mid}, value=${a[mid]}`);if(a[mid]<target)lo=mid+1;else hi=mid}lines.push(`result index = ${lo}; value = ${lo<a.length?a[lo]:'no match'}`);lab.querySelector('output').textContent=lines.join('\n')};lab.querySelector('input').oninput=update;update();
} else if (/^(22|27|32)-/.test(key)) {
 lab.innerHTML='<h3>Calculate average in-flight work</h3><p>For a stable system, L = arrival rate × average time. This teaching calculator does not predict latency percentiles.</p><label for="arrivals">Arrivals per second</label><input id="arrivals" type="range" min="10" max="200" step="10" value="80"><label for="duration">Average time in milliseconds</label><input id="duration" type="range" min="50" max="1000" step="50" value="250"><output aria-live="polite"></output>';
 const update=()=>{const rate=Number(lab.querySelector('#arrivals').value),ms=Number(lab.querySelector('#duration').value);lab.querySelector('output').textContent=`${rate} requests/s × ${ms}/1000 s = ${(rate*ms/1000).toFixed(1)} average in-flight requests`};lab.querySelectorAll('input').forEach(n=>n.oninput=update);update();
}

})();
