CREATE TABLE job_events(event_id VARCHAR(36) PRIMARY KEY, job_id VARCHAR(36) NOT NULL UNIQUE REFERENCES jobs(id), published BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE job_inbox(event_id VARCHAR(36) PRIMARY KEY, handled_at BIGINT NOT NULL);
