CREATE TABLE course(id BIGINT PRIMARY KEY, title VARCHAR(255), version BIGINT NOT NULL DEFAULT 0);
CREATE TABLE lesson(id BIGINT PRIMARY KEY, title VARCHAR(255), course_id BIGINT REFERENCES course(id));
CREATE TABLE outbox(id VARCHAR(36) PRIMARY KEY, payload VARCHAR(500) NOT NULL, delivered BOOLEAN NOT NULL DEFAULT FALSE);
